#!/bin/sh

set -o errexit

if [ $# = 0 ]; then
  echo >&2 "No packages specified"
  exit 1
fi

apt-get update
apt-get install -y --no-install-recommends -o DPkg::options::="--force-confdef" -o DPkg::options::="--force-confold" "$@"
apt-get clean -y
rm -rf \
   /var/cache/debconf/* \
   /var/lib/apt/lists/* \
   /var/log/* \
   /tmp/* \
   /var/tmp/* \
   /usr/share/doc/* \
   /usr/share/man/* \
   /usr/share/local/*
rm -f /var/lib/dpkg/statoverride